// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: omg/dds/descriptor.proto

#include "omg/dds/descriptor.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_omg_2fdds_2fdescriptor_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_MemberAnnotation_omg_2fdds_2fdescriptor_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_omg_2fdds_2fdescriptor_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_TypeAnnotation_omg_2fdds_2fdescriptor_2eproto;
namespace omg {
namespace dds {
class TypeAnnotationDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<TypeAnnotation> _instance;
} _TypeAnnotation_default_instance_;
class MemberAnnotationDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<MemberAnnotation> _instance;
} _MemberAnnotation_default_instance_;
}  // namespace dds
}  // namespace omg
static void InitDefaultsscc_info_MemberAnnotation_omg_2fdds_2fdescriptor_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::omg::dds::_MemberAnnotation_default_instance_;
    new (ptr) ::omg::dds::MemberAnnotation();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::omg::dds::MemberAnnotation::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_MemberAnnotation_omg_2fdds_2fdescriptor_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_MemberAnnotation_omg_2fdds_2fdescriptor_2eproto}, {}};

static void InitDefaultsscc_info_TypeAnnotation_omg_2fdds_2fdescriptor_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::omg::dds::_TypeAnnotation_default_instance_;
    new (ptr) ::omg::dds::TypeAnnotation();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::omg::dds::TypeAnnotation::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_TypeAnnotation_omg_2fdds_2fdescriptor_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_TypeAnnotation_omg_2fdds_2fdescriptor_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_omg_2fdds_2fdescriptor_2eproto[2];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_omg_2fdds_2fdescriptor_2eproto[3];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_omg_2fdds_2fdescriptor_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_omg_2fdds_2fdescriptor_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::omg::dds::TypeAnnotation, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::omg::dds::TypeAnnotation, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::omg::dds::TypeAnnotation, name_),
  PROTOBUF_FIELD_OFFSET(::omg::dds::TypeAnnotation, extensibility_),
  PROTOBUF_FIELD_OFFSET(::omg::dds::TypeAnnotation, default_id_),
  PROTOBUF_FIELD_OFFSET(::omg::dds::TypeAnnotation, auto_id_),
  0,
  1,
  2,
  3,
  PROTOBUF_FIELD_OFFSET(::omg::dds::MemberAnnotation, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::omg::dds::MemberAnnotation, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::omg::dds::MemberAnnotation, key_),
  PROTOBUF_FIELD_OFFSET(::omg::dds::MemberAnnotation, filterable_),
  PROTOBUF_FIELD_OFFSET(::omg::dds::MemberAnnotation, optional_),
  PROTOBUF_FIELD_OFFSET(::omg::dds::MemberAnnotation, default_id_),
  PROTOBUF_FIELD_OFFSET(::omg::dds::MemberAnnotation, id_),
  PROTOBUF_FIELD_OFFSET(::omg::dds::MemberAnnotation, hash_id_),
  1,
  2,
  3,
  4,
  5,
  0,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 9, sizeof(::omg::dds::TypeAnnotation)},
  { 13, 24, sizeof(::omg::dds::MemberAnnotation)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::omg::dds::_TypeAnnotation_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::omg::dds::_MemberAnnotation_default_instance_),
};

const char descriptor_table_protodef_omg_2fdds_2fdescriptor_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\030omg/dds/descriptor.proto\022\007omg.dds\032 goo"
  "gle/protobuf/descriptor.proto\"\243\001\n\016TypeAn"
  "notation\022\014\n\004name\030\001 \001(\t\0221\n\rextensibility\030"
  "\002 \001(\0162\032.omg.dds.ExtensibilityKind\022*\n\ndef"
  "ault_id\030\003 \001(\0162\026.omg.dds.DefaultIdKind\022$\n"
  "\007auto_id\030\004 \001(\0162\023.omg.dds.AutoIdKind\"\216\001\n\020"
  "MemberAnnotation\022\013\n\003key\030\001 \001(\010\022\022\n\nfiltera"
  "ble\030\002 \001(\010\022\020\n\010optional\030\003 \001(\010\022*\n\ndefault_i"
  "d\030\004 \001(\0162\026.omg.dds.DefaultIdKind\022\n\n\002id\030\005 "
  "\001(\r\022\017\n\007hash_id\030\006 \001(\t*;\n\021ExtensibilityKin"
  "d\022\013\n\007MUTABLE\020\000\022\016\n\nAPPENDABLE\020\001\022\t\n\005FINAL\020"
  "\002*<\n\rDefaultIdKind\022\027\n\023PROTOBUF_DEFAULT_I"
  "D\020\000\022\022\n\016DDS_DEFAULT_ID\020\001*6\n\nAutoIdKind\022\016\n"
  "\nNO_AUTO_ID\020\000\022\016\n\nSEQUENTIAL\020\001\022\010\n\004HASH\020\002:"
  "G\n\004type\022\037.google.protobuf.MessageOptions"
  "\030\3509 \001(\0132\027.omg.dds.TypeAnnotation:I\n\006memb"
  "er\022\035.google.protobuf.FieldOptions\030\3509 \001(\013"
  "2\031.omg.dds.MemberAnnotation"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_omg_2fdds_2fdescriptor_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_omg_2fdds_2fdescriptor_2eproto_sccs[2] = {
  &scc_info_MemberAnnotation_omg_2fdds_2fdescriptor_2eproto.base,
  &scc_info_TypeAnnotation_omg_2fdds_2fdescriptor_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_omg_2fdds_2fdescriptor_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_omg_2fdds_2fdescriptor_2eproto = {
  false, false, descriptor_table_protodef_omg_2fdds_2fdescriptor_2eproto, "omg/dds/descriptor.proto", 707,
  &descriptor_table_omg_2fdds_2fdescriptor_2eproto_once, descriptor_table_omg_2fdds_2fdescriptor_2eproto_sccs, descriptor_table_omg_2fdds_2fdescriptor_2eproto_deps, 2, 1,
  schemas, file_default_instances, TableStruct_omg_2fdds_2fdescriptor_2eproto::offsets,
  file_level_metadata_omg_2fdds_2fdescriptor_2eproto, 2, file_level_enum_descriptors_omg_2fdds_2fdescriptor_2eproto, file_level_service_descriptors_omg_2fdds_2fdescriptor_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_omg_2fdds_2fdescriptor_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_omg_2fdds_2fdescriptor_2eproto)), true);
namespace omg {
namespace dds {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ExtensibilityKind_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_omg_2fdds_2fdescriptor_2eproto);
  return file_level_enum_descriptors_omg_2fdds_2fdescriptor_2eproto[0];
}
bool ExtensibilityKind_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DefaultIdKind_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_omg_2fdds_2fdescriptor_2eproto);
  return file_level_enum_descriptors_omg_2fdds_2fdescriptor_2eproto[1];
}
bool DefaultIdKind_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AutoIdKind_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_omg_2fdds_2fdescriptor_2eproto);
  return file_level_enum_descriptors_omg_2fdds_2fdescriptor_2eproto[2];
}
bool AutoIdKind_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void TypeAnnotation::InitAsDefaultInstance() {
}
class TypeAnnotation::_Internal {
 public:
  using HasBits = decltype(std::declval<TypeAnnotation>()._has_bits_);
  static void set_has_name(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_extensibility(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_default_id(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_auto_id(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
};

TypeAnnotation::TypeAnnotation(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:omg.dds.TypeAnnotation)
}
TypeAnnotation::TypeAnnotation(const TypeAnnotation& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_name()) {
    name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_name(),
      GetArena());
  }
  ::memcpy(&extensibility_, &from.extensibility_,
    static_cast<size_t>(reinterpret_cast<char*>(&auto_id_) -
    reinterpret_cast<char*>(&extensibility_)) + sizeof(auto_id_));
  // @@protoc_insertion_point(copy_constructor:omg.dds.TypeAnnotation)
}

void TypeAnnotation::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_TypeAnnotation_omg_2fdds_2fdescriptor_2eproto.base);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&extensibility_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&auto_id_) -
      reinterpret_cast<char*>(&extensibility_)) + sizeof(auto_id_));
}

TypeAnnotation::~TypeAnnotation() {
  // @@protoc_insertion_point(destructor:omg.dds.TypeAnnotation)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void TypeAnnotation::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void TypeAnnotation::ArenaDtor(void* object) {
  TypeAnnotation* _this = reinterpret_cast< TypeAnnotation* >(object);
  (void)_this;
}
void TypeAnnotation::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void TypeAnnotation::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const TypeAnnotation& TypeAnnotation::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_TypeAnnotation_omg_2fdds_2fdescriptor_2eproto.base);
  return *internal_default_instance();
}


void TypeAnnotation::Clear() {
// @@protoc_insertion_point(message_clear_start:omg.dds.TypeAnnotation)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    name_.ClearNonDefaultToEmpty();
  }
  if (cached_has_bits & 0x0000000eu) {
    ::memset(&extensibility_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&auto_id_) -
        reinterpret_cast<char*>(&extensibility_)) + sizeof(auto_id_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TypeAnnotation::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // optional string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "omg.dds.TypeAnnotation.name");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .omg.dds.ExtensibilityKind extensibility = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::omg::dds::ExtensibilityKind_IsValid(val))) {
            _internal_set_extensibility(static_cast<::omg::dds::ExtensibilityKind>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(2, val, mutable_unknown_fields());
          }
        } else goto handle_unusual;
        continue;
      // optional .omg.dds.DefaultIdKind default_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::omg::dds::DefaultIdKind_IsValid(val))) {
            _internal_set_default_id(static_cast<::omg::dds::DefaultIdKind>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(3, val, mutable_unknown_fields());
          }
        } else goto handle_unusual;
        continue;
      // optional .omg.dds.AutoIdKind auto_id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::omg::dds::AutoIdKind_IsValid(val))) {
            _internal_set_auto_id(static_cast<::omg::dds::AutoIdKind>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(4, val, mutable_unknown_fields());
          }
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* TypeAnnotation::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:omg.dds.TypeAnnotation)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "omg.dds.TypeAnnotation.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // optional .omg.dds.ExtensibilityKind extensibility = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      2, this->_internal_extensibility(), target);
  }

  // optional .omg.dds.DefaultIdKind default_id = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      3, this->_internal_default_id(), target);
  }

  // optional .omg.dds.AutoIdKind auto_id = 4;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      4, this->_internal_auto_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:omg.dds.TypeAnnotation)
  return target;
}

size_t TypeAnnotation::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:omg.dds.TypeAnnotation)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    // optional string name = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_name());
    }

    // optional .omg.dds.ExtensibilityKind extensibility = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_extensibility());
    }

    // optional .omg.dds.DefaultIdKind default_id = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_default_id());
    }

    // optional .omg.dds.AutoIdKind auto_id = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_auto_id());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TypeAnnotation::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:omg.dds.TypeAnnotation)
  GOOGLE_DCHECK_NE(&from, this);
  const TypeAnnotation* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<TypeAnnotation>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:omg.dds.TypeAnnotation)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:omg.dds.TypeAnnotation)
    MergeFrom(*source);
  }
}

void TypeAnnotation::MergeFrom(const TypeAnnotation& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:omg.dds.TypeAnnotation)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_name(from._internal_name());
    }
    if (cached_has_bits & 0x00000002u) {
      extensibility_ = from.extensibility_;
    }
    if (cached_has_bits & 0x00000004u) {
      default_id_ = from.default_id_;
    }
    if (cached_has_bits & 0x00000008u) {
      auto_id_ = from.auto_id_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void TypeAnnotation::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:omg.dds.TypeAnnotation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TypeAnnotation::CopyFrom(const TypeAnnotation& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:omg.dds.TypeAnnotation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TypeAnnotation::IsInitialized() const {
  return true;
}

void TypeAnnotation::InternalSwap(TypeAnnotation* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  name_.Swap(&other->name_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TypeAnnotation, auto_id_)
      + sizeof(TypeAnnotation::auto_id_)
      - PROTOBUF_FIELD_OFFSET(TypeAnnotation, extensibility_)>(
          reinterpret_cast<char*>(&extensibility_),
          reinterpret_cast<char*>(&other->extensibility_));
}

::PROTOBUF_NAMESPACE_ID::Metadata TypeAnnotation::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void MemberAnnotation::InitAsDefaultInstance() {
}
class MemberAnnotation::_Internal {
 public:
  using HasBits = decltype(std::declval<MemberAnnotation>()._has_bits_);
  static void set_has_key(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_filterable(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_optional(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_default_id(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_id(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_hash_id(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

MemberAnnotation::MemberAnnotation(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:omg.dds.MemberAnnotation)
}
MemberAnnotation::MemberAnnotation(const MemberAnnotation& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  hash_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_hash_id()) {
    hash_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_hash_id(),
      GetArena());
  }
  ::memcpy(&key_, &from.key_,
    static_cast<size_t>(reinterpret_cast<char*>(&id_) -
    reinterpret_cast<char*>(&key_)) + sizeof(id_));
  // @@protoc_insertion_point(copy_constructor:omg.dds.MemberAnnotation)
}

void MemberAnnotation::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_MemberAnnotation_omg_2fdds_2fdescriptor_2eproto.base);
  hash_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&key_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&id_) -
      reinterpret_cast<char*>(&key_)) + sizeof(id_));
}

MemberAnnotation::~MemberAnnotation() {
  // @@protoc_insertion_point(destructor:omg.dds.MemberAnnotation)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void MemberAnnotation::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  hash_id_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void MemberAnnotation::ArenaDtor(void* object) {
  MemberAnnotation* _this = reinterpret_cast< MemberAnnotation* >(object);
  (void)_this;
}
void MemberAnnotation::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void MemberAnnotation::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const MemberAnnotation& MemberAnnotation::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_MemberAnnotation_omg_2fdds_2fdescriptor_2eproto.base);
  return *internal_default_instance();
}


void MemberAnnotation::Clear() {
// @@protoc_insertion_point(message_clear_start:omg.dds.MemberAnnotation)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    hash_id_.ClearNonDefaultToEmpty();
  }
  if (cached_has_bits & 0x0000003eu) {
    ::memset(&key_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&id_) -
        reinterpret_cast<char*>(&key_)) + sizeof(id_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MemberAnnotation::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // optional bool key = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          _Internal::set_has_key(&has_bits);
          key_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional bool filterable = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          _Internal::set_has_filterable(&has_bits);
          filterable_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional bool optional = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          _Internal::set_has_optional(&has_bits);
          optional_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .omg.dds.DefaultIdKind default_id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::omg::dds::DefaultIdKind_IsValid(val))) {
            _internal_set_default_id(static_cast<::omg::dds::DefaultIdKind>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(4, val, mutable_unknown_fields());
          }
        } else goto handle_unusual;
        continue;
      // optional uint32 id = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          _Internal::set_has_id(&has_bits);
          id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional string hash_id = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          auto str = _internal_mutable_hash_id();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "omg.dds.MemberAnnotation.hash_id");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* MemberAnnotation::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:omg.dds.MemberAnnotation)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional bool key = 1;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(1, this->_internal_key(), target);
  }

  // optional bool filterable = 2;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(2, this->_internal_filterable(), target);
  }

  // optional bool optional = 3;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(3, this->_internal_optional(), target);
  }

  // optional .omg.dds.DefaultIdKind default_id = 4;
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      4, this->_internal_default_id(), target);
  }

  // optional uint32 id = 5;
  if (cached_has_bits & 0x00000020u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(5, this->_internal_id(), target);
  }

  // optional string hash_id = 6;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_hash_id().data(), static_cast<int>(this->_internal_hash_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "omg.dds.MemberAnnotation.hash_id");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_hash_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:omg.dds.MemberAnnotation)
  return target;
}

size_t MemberAnnotation::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:omg.dds.MemberAnnotation)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    // optional string hash_id = 6;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_hash_id());
    }

    // optional bool key = 1;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + 1;
    }

    // optional bool filterable = 2;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 + 1;
    }

    // optional bool optional = 3;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 + 1;
    }

    // optional .omg.dds.DefaultIdKind default_id = 4;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_default_id());
    }

    // optional uint32 id = 5;
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
          this->_internal_id());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MemberAnnotation::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:omg.dds.MemberAnnotation)
  GOOGLE_DCHECK_NE(&from, this);
  const MemberAnnotation* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<MemberAnnotation>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:omg.dds.MemberAnnotation)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:omg.dds.MemberAnnotation)
    MergeFrom(*source);
  }
}

void MemberAnnotation::MergeFrom(const MemberAnnotation& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:omg.dds.MemberAnnotation)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_hash_id(from._internal_hash_id());
    }
    if (cached_has_bits & 0x00000002u) {
      key_ = from.key_;
    }
    if (cached_has_bits & 0x00000004u) {
      filterable_ = from.filterable_;
    }
    if (cached_has_bits & 0x00000008u) {
      optional_ = from.optional_;
    }
    if (cached_has_bits & 0x00000010u) {
      default_id_ = from.default_id_;
    }
    if (cached_has_bits & 0x00000020u) {
      id_ = from.id_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void MemberAnnotation::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:omg.dds.MemberAnnotation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MemberAnnotation::CopyFrom(const MemberAnnotation& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:omg.dds.MemberAnnotation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MemberAnnotation::IsInitialized() const {
  return true;
}

void MemberAnnotation::InternalSwap(MemberAnnotation* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  hash_id_.Swap(&other->hash_id_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MemberAnnotation, id_)
      + sizeof(MemberAnnotation::id_)
      - PROTOBUF_FIELD_OFFSET(MemberAnnotation, key_)>(
          reinterpret_cast<char*>(&key_),
          reinterpret_cast<char*>(&other->key_));
}

::PROTOBUF_NAMESPACE_ID::Metadata MemberAnnotation::GetMetadata() const {
  return GetMetadataStatic();
}

::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::MessageTypeTraits< ::omg::dds::TypeAnnotation >, 11, false >
  type(kTypeFieldNumber, ::omg::dds::TypeAnnotation::default_instance());
::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::MessageTypeTraits< ::omg::dds::MemberAnnotation >, 11, false >
  member(kMemberFieldNumber, ::omg::dds::MemberAnnotation::default_instance());

// @@protoc_insertion_point(namespace_scope)
}  // namespace dds
}  // namespace omg
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::omg::dds::TypeAnnotation* Arena::CreateMaybeMessage< ::omg::dds::TypeAnnotation >(Arena* arena) {
  return Arena::CreateMessageInternal< ::omg::dds::TypeAnnotation >(arena);
}
template<> PROTOBUF_NOINLINE ::omg::dds::MemberAnnotation* Arena::CreateMaybeMessage< ::omg::dds::MemberAnnotation >(Arena* arena) {
  return Arena::CreateMessageInternal< ::omg::dds::MemberAnnotation >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
