// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: omg/dds/descriptor.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_omg_2fdds_2fdescriptor_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_omg_2fdds_2fdescriptor_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/descriptor.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_omg_2fdds_2fdescriptor_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_omg_2fdds_2fdescriptor_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_omg_2fdds_2fdescriptor_2eproto;
namespace omg {
namespace dds {
class MemberAnnotation;
class MemberAnnotationDefaultTypeInternal;
extern MemberAnnotationDefaultTypeInternal _MemberAnnotation_default_instance_;
class TypeAnnotation;
class TypeAnnotationDefaultTypeInternal;
extern TypeAnnotationDefaultTypeInternal _TypeAnnotation_default_instance_;
}  // namespace dds
}  // namespace omg
PROTOBUF_NAMESPACE_OPEN
template<> ::omg::dds::MemberAnnotation* Arena::CreateMaybeMessage<::omg::dds::MemberAnnotation>(Arena*);
template<> ::omg::dds::TypeAnnotation* Arena::CreateMaybeMessage<::omg::dds::TypeAnnotation>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace omg {
namespace dds {

enum ExtensibilityKind : int {
  MUTABLE = 0,
  APPENDABLE = 1,
  FINAL = 2
};
bool ExtensibilityKind_IsValid(int value);
constexpr ExtensibilityKind ExtensibilityKind_MIN = MUTABLE;
constexpr ExtensibilityKind ExtensibilityKind_MAX = FINAL;
constexpr int ExtensibilityKind_ARRAYSIZE = ExtensibilityKind_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ExtensibilityKind_descriptor();
template<typename T>
inline const std::string& ExtensibilityKind_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ExtensibilityKind>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ExtensibilityKind_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ExtensibilityKind_descriptor(), enum_t_value);
}
inline bool ExtensibilityKind_Parse(
    const std::string& name, ExtensibilityKind* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ExtensibilityKind>(
    ExtensibilityKind_descriptor(), name, value);
}
enum DefaultIdKind : int {
  PROTOBUF_DEFAULT_ID = 0,
  DDS_DEFAULT_ID = 1
};
bool DefaultIdKind_IsValid(int value);
constexpr DefaultIdKind DefaultIdKind_MIN = PROTOBUF_DEFAULT_ID;
constexpr DefaultIdKind DefaultIdKind_MAX = DDS_DEFAULT_ID;
constexpr int DefaultIdKind_ARRAYSIZE = DefaultIdKind_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DefaultIdKind_descriptor();
template<typename T>
inline const std::string& DefaultIdKind_Name(T enum_t_value) {
  static_assert(::std::is_same<T, DefaultIdKind>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function DefaultIdKind_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    DefaultIdKind_descriptor(), enum_t_value);
}
inline bool DefaultIdKind_Parse(
    const std::string& name, DefaultIdKind* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<DefaultIdKind>(
    DefaultIdKind_descriptor(), name, value);
}
enum AutoIdKind : int {
  NO_AUTO_ID = 0,
  SEQUENTIAL = 1,
  HASH = 2
};
bool AutoIdKind_IsValid(int value);
constexpr AutoIdKind AutoIdKind_MIN = NO_AUTO_ID;
constexpr AutoIdKind AutoIdKind_MAX = HASH;
constexpr int AutoIdKind_ARRAYSIZE = AutoIdKind_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AutoIdKind_descriptor();
template<typename T>
inline const std::string& AutoIdKind_Name(T enum_t_value) {
  static_assert(::std::is_same<T, AutoIdKind>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function AutoIdKind_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    AutoIdKind_descriptor(), enum_t_value);
}
inline bool AutoIdKind_Parse(
    const std::string& name, AutoIdKind* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<AutoIdKind>(
    AutoIdKind_descriptor(), name, value);
}
// ===================================================================

class TypeAnnotation PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:omg.dds.TypeAnnotation) */ {
 public:
  inline TypeAnnotation() : TypeAnnotation(nullptr) {};
  virtual ~TypeAnnotation();

  TypeAnnotation(const TypeAnnotation& from);
  TypeAnnotation(TypeAnnotation&& from) noexcept
    : TypeAnnotation() {
    *this = ::std::move(from);
  }

  inline TypeAnnotation& operator=(const TypeAnnotation& from) {
    CopyFrom(from);
    return *this;
  }
  inline TypeAnnotation& operator=(TypeAnnotation&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TypeAnnotation& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TypeAnnotation* internal_default_instance() {
    return reinterpret_cast<const TypeAnnotation*>(
               &_TypeAnnotation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TypeAnnotation& a, TypeAnnotation& b) {
    a.Swap(&b);
  }
  inline void Swap(TypeAnnotation* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TypeAnnotation* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TypeAnnotation* New() const final {
    return CreateMaybeMessage<TypeAnnotation>(nullptr);
  }

  TypeAnnotation* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TypeAnnotation>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TypeAnnotation& from);
  void MergeFrom(const TypeAnnotation& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TypeAnnotation* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "omg.dds.TypeAnnotation";
  }
  protected:
  explicit TypeAnnotation(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_omg_2fdds_2fdescriptor_2eproto);
    return ::descriptor_table_omg_2fdds_2fdescriptor_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kExtensibilityFieldNumber = 2,
    kDefaultIdFieldNumber = 3,
    kAutoIdFieldNumber = 4,
  };
  // optional string name = 1;
  bool has_name() const;
  private:
  bool _internal_has_name() const;
  public:
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_name();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_name(
      std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // optional .omg.dds.ExtensibilityKind extensibility = 2;
  bool has_extensibility() const;
  private:
  bool _internal_has_extensibility() const;
  public:
  void clear_extensibility();
  ::omg::dds::ExtensibilityKind extensibility() const;
  void set_extensibility(::omg::dds::ExtensibilityKind value);
  private:
  ::omg::dds::ExtensibilityKind _internal_extensibility() const;
  void _internal_set_extensibility(::omg::dds::ExtensibilityKind value);
  public:

  // optional .omg.dds.DefaultIdKind default_id = 3;
  bool has_default_id() const;
  private:
  bool _internal_has_default_id() const;
  public:
  void clear_default_id();
  ::omg::dds::DefaultIdKind default_id() const;
  void set_default_id(::omg::dds::DefaultIdKind value);
  private:
  ::omg::dds::DefaultIdKind _internal_default_id() const;
  void _internal_set_default_id(::omg::dds::DefaultIdKind value);
  public:

  // optional .omg.dds.AutoIdKind auto_id = 4;
  bool has_auto_id() const;
  private:
  bool _internal_has_auto_id() const;
  public:
  void clear_auto_id();
  ::omg::dds::AutoIdKind auto_id() const;
  void set_auto_id(::omg::dds::AutoIdKind value);
  private:
  ::omg::dds::AutoIdKind _internal_auto_id() const;
  void _internal_set_auto_id(::omg::dds::AutoIdKind value);
  public:

  // @@protoc_insertion_point(class_scope:omg.dds.TypeAnnotation)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  int extensibility_;
  int default_id_;
  int auto_id_;
  friend struct ::TableStruct_omg_2fdds_2fdescriptor_2eproto;
};
// -------------------------------------------------------------------

class MemberAnnotation PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:omg.dds.MemberAnnotation) */ {
 public:
  inline MemberAnnotation() : MemberAnnotation(nullptr) {};
  virtual ~MemberAnnotation();

  MemberAnnotation(const MemberAnnotation& from);
  MemberAnnotation(MemberAnnotation&& from) noexcept
    : MemberAnnotation() {
    *this = ::std::move(from);
  }

  inline MemberAnnotation& operator=(const MemberAnnotation& from) {
    CopyFrom(from);
    return *this;
  }
  inline MemberAnnotation& operator=(MemberAnnotation&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MemberAnnotation& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MemberAnnotation* internal_default_instance() {
    return reinterpret_cast<const MemberAnnotation*>(
               &_MemberAnnotation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(MemberAnnotation& a, MemberAnnotation& b) {
    a.Swap(&b);
  }
  inline void Swap(MemberAnnotation* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MemberAnnotation* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MemberAnnotation* New() const final {
    return CreateMaybeMessage<MemberAnnotation>(nullptr);
  }

  MemberAnnotation* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MemberAnnotation>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MemberAnnotation& from);
  void MergeFrom(const MemberAnnotation& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MemberAnnotation* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "omg.dds.MemberAnnotation";
  }
  protected:
  explicit MemberAnnotation(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_omg_2fdds_2fdescriptor_2eproto);
    return ::descriptor_table_omg_2fdds_2fdescriptor_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHashIdFieldNumber = 6,
    kKeyFieldNumber = 1,
    kFilterableFieldNumber = 2,
    kOptionalFieldNumber = 3,
    kDefaultIdFieldNumber = 4,
    kIdFieldNumber = 5,
  };
  // optional string hash_id = 6;
  bool has_hash_id() const;
  private:
  bool _internal_has_hash_id() const;
  public:
  void clear_hash_id();
  const std::string& hash_id() const;
  void set_hash_id(const std::string& value);
  void set_hash_id(std::string&& value);
  void set_hash_id(const char* value);
  void set_hash_id(const char* value, size_t size);
  std::string* mutable_hash_id();
  std::string* release_hash_id();
  void set_allocated_hash_id(std::string* hash_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_hash_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_hash_id(
      std::string* hash_id);
  private:
  const std::string& _internal_hash_id() const;
  void _internal_set_hash_id(const std::string& value);
  std::string* _internal_mutable_hash_id();
  public:

  // optional bool key = 1;
  bool has_key() const;
  private:
  bool _internal_has_key() const;
  public:
  void clear_key();
  bool key() const;
  void set_key(bool value);
  private:
  bool _internal_key() const;
  void _internal_set_key(bool value);
  public:

  // optional bool filterable = 2;
  bool has_filterable() const;
  private:
  bool _internal_has_filterable() const;
  public:
  void clear_filterable();
  bool filterable() const;
  void set_filterable(bool value);
  private:
  bool _internal_filterable() const;
  void _internal_set_filterable(bool value);
  public:

  // optional bool optional = 3;
  bool has_optional() const;
  private:
  bool _internal_has_optional() const;
  public:
  void clear_optional();
  bool optional() const;
  void set_optional(bool value);
  private:
  bool _internal_optional() const;
  void _internal_set_optional(bool value);
  public:

  // optional .omg.dds.DefaultIdKind default_id = 4;
  bool has_default_id() const;
  private:
  bool _internal_has_default_id() const;
  public:
  void clear_default_id();
  ::omg::dds::DefaultIdKind default_id() const;
  void set_default_id(::omg::dds::DefaultIdKind value);
  private:
  ::omg::dds::DefaultIdKind _internal_default_id() const;
  void _internal_set_default_id(::omg::dds::DefaultIdKind value);
  public:

  // optional uint32 id = 5;
  bool has_id() const;
  private:
  bool _internal_has_id() const;
  public:
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_id() const;
  void _internal_set_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:omg.dds.MemberAnnotation)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr hash_id_;
  bool key_;
  bool filterable_;
  bool optional_;
  int default_id_;
  ::PROTOBUF_NAMESPACE_ID::uint32 id_;
  friend struct ::TableStruct_omg_2fdds_2fdescriptor_2eproto;
};
// ===================================================================

static const int kTypeFieldNumber = 7400;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::MessageTypeTraits< ::omg::dds::TypeAnnotation >, 11, false >
  type;
static const int kMemberFieldNumber = 7400;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::MessageTypeTraits< ::omg::dds::MemberAnnotation >, 11, false >
  member;

// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TypeAnnotation

// optional string name = 1;
inline bool TypeAnnotation::_internal_has_name() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool TypeAnnotation::has_name() const {
  return _internal_has_name();
}
inline void TypeAnnotation::clear_name() {
  name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& TypeAnnotation::name() const {
  // @@protoc_insertion_point(field_get:omg.dds.TypeAnnotation.name)
  return _internal_name();
}
inline void TypeAnnotation::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:omg.dds.TypeAnnotation.name)
}
inline std::string* TypeAnnotation::mutable_name() {
  // @@protoc_insertion_point(field_mutable:omg.dds.TypeAnnotation.name)
  return _internal_mutable_name();
}
inline const std::string& TypeAnnotation::_internal_name() const {
  return name_.Get();
}
inline void TypeAnnotation::_internal_set_name(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void TypeAnnotation::set_name(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  name_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:omg.dds.TypeAnnotation.name)
}
inline void TypeAnnotation::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:omg.dds.TypeAnnotation.name)
}
inline void TypeAnnotation::set_name(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:omg.dds.TypeAnnotation.name)
}
inline std::string* TypeAnnotation::_internal_mutable_name() {
  _has_bits_[0] |= 0x00000001u;
  return name_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* TypeAnnotation::release_name() {
  // @@protoc_insertion_point(field_release:omg.dds.TypeAnnotation.name)
  if (!_internal_has_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return name_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void TypeAnnotation::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:omg.dds.TypeAnnotation.name)
}
inline std::string* TypeAnnotation::unsafe_arena_release_name() {
  // @@protoc_insertion_point(field_unsafe_arena_release:omg.dds.TypeAnnotation.name)
  GOOGLE_DCHECK(GetArena() != nullptr);
  _has_bits_[0] &= ~0x00000001u;
  return name_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void TypeAnnotation::unsafe_arena_set_allocated_name(
    std::string* name) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  name_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      name, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:omg.dds.TypeAnnotation.name)
}

// optional .omg.dds.ExtensibilityKind extensibility = 2;
inline bool TypeAnnotation::_internal_has_extensibility() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool TypeAnnotation::has_extensibility() const {
  return _internal_has_extensibility();
}
inline void TypeAnnotation::clear_extensibility() {
  extensibility_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::omg::dds::ExtensibilityKind TypeAnnotation::_internal_extensibility() const {
  return static_cast< ::omg::dds::ExtensibilityKind >(extensibility_);
}
inline ::omg::dds::ExtensibilityKind TypeAnnotation::extensibility() const {
  // @@protoc_insertion_point(field_get:omg.dds.TypeAnnotation.extensibility)
  return _internal_extensibility();
}
inline void TypeAnnotation::_internal_set_extensibility(::omg::dds::ExtensibilityKind value) {
  assert(::omg::dds::ExtensibilityKind_IsValid(value));
  _has_bits_[0] |= 0x00000002u;
  extensibility_ = value;
}
inline void TypeAnnotation::set_extensibility(::omg::dds::ExtensibilityKind value) {
  _internal_set_extensibility(value);
  // @@protoc_insertion_point(field_set:omg.dds.TypeAnnotation.extensibility)
}

// optional .omg.dds.DefaultIdKind default_id = 3;
inline bool TypeAnnotation::_internal_has_default_id() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool TypeAnnotation::has_default_id() const {
  return _internal_has_default_id();
}
inline void TypeAnnotation::clear_default_id() {
  default_id_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::omg::dds::DefaultIdKind TypeAnnotation::_internal_default_id() const {
  return static_cast< ::omg::dds::DefaultIdKind >(default_id_);
}
inline ::omg::dds::DefaultIdKind TypeAnnotation::default_id() const {
  // @@protoc_insertion_point(field_get:omg.dds.TypeAnnotation.default_id)
  return _internal_default_id();
}
inline void TypeAnnotation::_internal_set_default_id(::omg::dds::DefaultIdKind value) {
  assert(::omg::dds::DefaultIdKind_IsValid(value));
  _has_bits_[0] |= 0x00000004u;
  default_id_ = value;
}
inline void TypeAnnotation::set_default_id(::omg::dds::DefaultIdKind value) {
  _internal_set_default_id(value);
  // @@protoc_insertion_point(field_set:omg.dds.TypeAnnotation.default_id)
}

// optional .omg.dds.AutoIdKind auto_id = 4;
inline bool TypeAnnotation::_internal_has_auto_id() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool TypeAnnotation::has_auto_id() const {
  return _internal_has_auto_id();
}
inline void TypeAnnotation::clear_auto_id() {
  auto_id_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::omg::dds::AutoIdKind TypeAnnotation::_internal_auto_id() const {
  return static_cast< ::omg::dds::AutoIdKind >(auto_id_);
}
inline ::omg::dds::AutoIdKind TypeAnnotation::auto_id() const {
  // @@protoc_insertion_point(field_get:omg.dds.TypeAnnotation.auto_id)
  return _internal_auto_id();
}
inline void TypeAnnotation::_internal_set_auto_id(::omg::dds::AutoIdKind value) {
  assert(::omg::dds::AutoIdKind_IsValid(value));
  _has_bits_[0] |= 0x00000008u;
  auto_id_ = value;
}
inline void TypeAnnotation::set_auto_id(::omg::dds::AutoIdKind value) {
  _internal_set_auto_id(value);
  // @@protoc_insertion_point(field_set:omg.dds.TypeAnnotation.auto_id)
}

// -------------------------------------------------------------------

// MemberAnnotation

// optional bool key = 1;
inline bool MemberAnnotation::_internal_has_key() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool MemberAnnotation::has_key() const {
  return _internal_has_key();
}
inline void MemberAnnotation::clear_key() {
  key_ = false;
  _has_bits_[0] &= ~0x00000002u;
}
inline bool MemberAnnotation::_internal_key() const {
  return key_;
}
inline bool MemberAnnotation::key() const {
  // @@protoc_insertion_point(field_get:omg.dds.MemberAnnotation.key)
  return _internal_key();
}
inline void MemberAnnotation::_internal_set_key(bool value) {
  _has_bits_[0] |= 0x00000002u;
  key_ = value;
}
inline void MemberAnnotation::set_key(bool value) {
  _internal_set_key(value);
  // @@protoc_insertion_point(field_set:omg.dds.MemberAnnotation.key)
}

// optional bool filterable = 2;
inline bool MemberAnnotation::_internal_has_filterable() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool MemberAnnotation::has_filterable() const {
  return _internal_has_filterable();
}
inline void MemberAnnotation::clear_filterable() {
  filterable_ = false;
  _has_bits_[0] &= ~0x00000004u;
}
inline bool MemberAnnotation::_internal_filterable() const {
  return filterable_;
}
inline bool MemberAnnotation::filterable() const {
  // @@protoc_insertion_point(field_get:omg.dds.MemberAnnotation.filterable)
  return _internal_filterable();
}
inline void MemberAnnotation::_internal_set_filterable(bool value) {
  _has_bits_[0] |= 0x00000004u;
  filterable_ = value;
}
inline void MemberAnnotation::set_filterable(bool value) {
  _internal_set_filterable(value);
  // @@protoc_insertion_point(field_set:omg.dds.MemberAnnotation.filterable)
}

// optional bool optional = 3;
inline bool MemberAnnotation::_internal_has_optional() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool MemberAnnotation::has_optional() const {
  return _internal_has_optional();
}
inline void MemberAnnotation::clear_optional() {
  optional_ = false;
  _has_bits_[0] &= ~0x00000008u;
}
inline bool MemberAnnotation::_internal_optional() const {
  return optional_;
}
inline bool MemberAnnotation::optional() const {
  // @@protoc_insertion_point(field_get:omg.dds.MemberAnnotation.optional)
  return _internal_optional();
}
inline void MemberAnnotation::_internal_set_optional(bool value) {
  _has_bits_[0] |= 0x00000008u;
  optional_ = value;
}
inline void MemberAnnotation::set_optional(bool value) {
  _internal_set_optional(value);
  // @@protoc_insertion_point(field_set:omg.dds.MemberAnnotation.optional)
}

// optional .omg.dds.DefaultIdKind default_id = 4;
inline bool MemberAnnotation::_internal_has_default_id() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool MemberAnnotation::has_default_id() const {
  return _internal_has_default_id();
}
inline void MemberAnnotation::clear_default_id() {
  default_id_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::omg::dds::DefaultIdKind MemberAnnotation::_internal_default_id() const {
  return static_cast< ::omg::dds::DefaultIdKind >(default_id_);
}
inline ::omg::dds::DefaultIdKind MemberAnnotation::default_id() const {
  // @@protoc_insertion_point(field_get:omg.dds.MemberAnnotation.default_id)
  return _internal_default_id();
}
inline void MemberAnnotation::_internal_set_default_id(::omg::dds::DefaultIdKind value) {
  assert(::omg::dds::DefaultIdKind_IsValid(value));
  _has_bits_[0] |= 0x00000010u;
  default_id_ = value;
}
inline void MemberAnnotation::set_default_id(::omg::dds::DefaultIdKind value) {
  _internal_set_default_id(value);
  // @@protoc_insertion_point(field_set:omg.dds.MemberAnnotation.default_id)
}

// optional uint32 id = 5;
inline bool MemberAnnotation::_internal_has_id() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool MemberAnnotation::has_id() const {
  return _internal_has_id();
}
inline void MemberAnnotation::clear_id() {
  id_ = 0u;
  _has_bits_[0] &= ~0x00000020u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 MemberAnnotation::_internal_id() const {
  return id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 MemberAnnotation::id() const {
  // @@protoc_insertion_point(field_get:omg.dds.MemberAnnotation.id)
  return _internal_id();
}
inline void MemberAnnotation::_internal_set_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000020u;
  id_ = value;
}
inline void MemberAnnotation::set_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:omg.dds.MemberAnnotation.id)
}

// optional string hash_id = 6;
inline bool MemberAnnotation::_internal_has_hash_id() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool MemberAnnotation::has_hash_id() const {
  return _internal_has_hash_id();
}
inline void MemberAnnotation::clear_hash_id() {
  hash_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& MemberAnnotation::hash_id() const {
  // @@protoc_insertion_point(field_get:omg.dds.MemberAnnotation.hash_id)
  return _internal_hash_id();
}
inline void MemberAnnotation::set_hash_id(const std::string& value) {
  _internal_set_hash_id(value);
  // @@protoc_insertion_point(field_set:omg.dds.MemberAnnotation.hash_id)
}
inline std::string* MemberAnnotation::mutable_hash_id() {
  // @@protoc_insertion_point(field_mutable:omg.dds.MemberAnnotation.hash_id)
  return _internal_mutable_hash_id();
}
inline const std::string& MemberAnnotation::_internal_hash_id() const {
  return hash_id_.Get();
}
inline void MemberAnnotation::_internal_set_hash_id(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  hash_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void MemberAnnotation::set_hash_id(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  hash_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:omg.dds.MemberAnnotation.hash_id)
}
inline void MemberAnnotation::set_hash_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  hash_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:omg.dds.MemberAnnotation.hash_id)
}
inline void MemberAnnotation::set_hash_id(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  hash_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:omg.dds.MemberAnnotation.hash_id)
}
inline std::string* MemberAnnotation::_internal_mutable_hash_id() {
  _has_bits_[0] |= 0x00000001u;
  return hash_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* MemberAnnotation::release_hash_id() {
  // @@protoc_insertion_point(field_release:omg.dds.MemberAnnotation.hash_id)
  if (!_internal_has_hash_id()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return hash_id_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void MemberAnnotation::set_allocated_hash_id(std::string* hash_id) {
  if (hash_id != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  hash_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), hash_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:omg.dds.MemberAnnotation.hash_id)
}
inline std::string* MemberAnnotation::unsafe_arena_release_hash_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:omg.dds.MemberAnnotation.hash_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  _has_bits_[0] &= ~0x00000001u;
  return hash_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void MemberAnnotation::unsafe_arena_set_allocated_hash_id(
    std::string* hash_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (hash_id != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  hash_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      hash_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:omg.dds.MemberAnnotation.hash_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace dds
}  // namespace omg

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::omg::dds::ExtensibilityKind> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::omg::dds::ExtensibilityKind>() {
  return ::omg::dds::ExtensibilityKind_descriptor();
}
template <> struct is_proto_enum< ::omg::dds::DefaultIdKind> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::omg::dds::DefaultIdKind>() {
  return ::omg::dds::DefaultIdKind_descriptor();
}
template <> struct is_proto_enum< ::omg::dds::AutoIdKind> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::omg::dds::AutoIdKind>() {
  return ::omg::dds::AutoIdKind_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_omg_2fdds_2fdescriptor_2eproto
